version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-positions
    ports:
      - '6510:5432'
    volumes:
      - postgresPositionsDB:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgresPositionsDB:
